### ISSUE TITLE
Abacus.animation internal method cacheKeys() needs review

### ISSUE THREAD

**Issue by rwaldron** [Abacus/Abacus#57]
I'm not sure how to describe this, but if you put a console.log in the function, just before the return `console.log( keys )` and then run the test suite, you'll see that it's creating some bogus looking arrays, mostly when it deals with Float32Arrays

**Comment by mzgoddard** [comment]
cacheKeys should have less bogus looking arrays for non-typed-array objects. If there are, I'd like to see some examples.

I know about the bogus looking arrays for typed arrays. I am going to add logic like Abacus.clone's different handling of Arrays, Typed Arrays, and other Objects to cacheKeys and cacheTweenable to make them handle Arrays and Typed Arrays more intelligently.

Typed arrays are strange in comparison to arrays. The objects contain useful values for reflection but since cacheKeys isn't smart enough in its reflection it saves those values too, which will unnecessarily slows down doTween later on.

**Comment by rwaldron** [comment]
Why can't you iterate the arrays with regular `for( ; ; )` instead of `for ( in )`?

**Comment by mzgoddard** [comment]
I can. That is what I am doing now. I just had a more (/too) generic version earlier since it needs to handle objects too.

Also I think the parseInt stuff I wrote is dumb. So I am getting rid of it too.
